### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by shaktech786** [jane/react-dwolla-iav#11]
Hey guys, thanks for fixing the onSuccess bug super quickly! I was wondering if you guys could also allow for a data-testid prop? I'm trying to see if the Dwolla component renders in a react-testing-library test but when I put a data-testid prop on there it still can't find it.

**Comment by zacanger** [comment]
Sorry, somehow this issue slipped by. Just pushed a change allowing it to take a `testID` prop, which gets turned into a `data-testid` attribute. The name choice for the prop there is for compatibility with React Native. Please let us know if version 2.1.0 works for you.
