### ISSUE TITLE
How to add loader until the dwolla form is loaded

### ISSUE THREAD

**Issue by adityay-perpetualny** [jane/react-dwolla-iav#2]

**Comment by TomPridham** [comment]
can you give us some more info on what you're looking for? do you want a loader while the script is loading or while the dwolla popup is loading?

**Comment by greyivy** [comment]
You can listen for any subscriber event.
```javascript
dwollaConfig: {
  ...
  subscriber: () => this.setState({ isLoading: false }),
}
```

**Comment by zacanger** [comment]
Thanks @greyivy! @adityay-perpetualny does that solve your issue?

**Comment by zacanger** [comment]
@adityay-perpetualny I'm going to close this, please reopen if the above answer doesn't work for you.

**Comment by raju-ncrts** [comment]
Any solutions of this question?
